name: calendar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #loop_page_view: ^1.2.5
  #infinite_listview: ^1.1.0
  #sqflite: ^2.3.0
  #sqflite_common_ffi_web: ^0.4.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_native_splash: ^2.3.4

flutter_native_splash:
  background_image: "assets/inicio.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
