name: calendar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_native_splash: ^2.3.4
  firebase_auth: ^4.11.1

flutter_native_splash:
  background_image: "assets/inicio.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
