// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7c70hb-V9d858vauGFjJjqPy7dpV3Ixc',
    appId: '1:758770303658:web:c4b94e74c75174f0cc86d3',
    messagingSenderId: '758770303658',
    projectId: 'unireserva-b3c68',
    authDomain: 'unireserva-b3c68.firebaseapp.com',
    storageBucket: 'unireserva-b3c68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlYzH1NiFhe3KgehQmlvJMWfvGSOrKPtc',
    appId: '1:758770303658:android:71b2131e2934f3dbcc86d3',
    messagingSenderId: '758770303658',
    projectId: 'unireserva-b3c68',
    storageBucket: 'unireserva-b3c68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_MPMgrbqay6zJvn3WCFHeu1SZ1z0T7Q8',
    appId: '1:758770303658:ios:182b51ec82fa9bb6cc86d3',
    messagingSenderId: '758770303658',
    projectId: 'unireserva-b3c68',
    storageBucket: 'unireserva-b3c68.appspot.com',
    iosBundleId: 'com.example.calendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_MPMgrbqay6zJvn3WCFHeu1SZ1z0T7Q8',
    appId: '1:758770303658:ios:9f2da2df1f088ab3cc86d3',
    messagingSenderId: '758770303658',
    projectId: 'unireserva-b3c68',
    storageBucket: 'unireserva-b3c68.appspot.com',
    iosBundleId: 'com.example.calendar.RunnerTests',
  );
}
